#!/bin/bash
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:~/bin
export sh=/usr/bin/reok
export sh_new="https://raw.githubusercontent.com/4055020/shell/master/reok"
export sh_ver="https://raw.githubusercontent.com/4055020/shell/master/config"

#设置颜色
export RGB31="\033[31m"				#红	错误
export RGB33="\033[33m"				#黄	提示
export RGB36="\033[36m"				#蓝	回显
export RGB32="\033[32m"				#绿	成功
export RGB35="\033[35m"				#紫	
export RGB40="echo -en \\033[1;30m"	#灰	默认
export RGB="\033[0m"				#关

function check_shell(){
    info=`curl -s -m 10 --connect-timeout 10 -I https://raw.githubusercontent.com/4055020/shell/master/shell/$1.sh`
    code=`echo $info|grep "HTTP"|awk '{print $2}'`
    if [ "$code" == "200" ];then
        bash -c "$(curl -sS https://raw.githubusercontent.com/4055020/shell/master/shell/$1.sh)"
    else
        echo "尚未支持的命令$1"$1
    fi
}

function check_sus(){
if [ ! -e $sh ]; then
	wget --no-check-certificate -qO $sh $sh_new && chmod 777 $sh && echo -e 请直接直接带指令执行例${RGB33}reok help && exit 0
else
	new_ver=$(wget --no-check-certificate -qO- $sh_ver|grep 'ver="'|awk -F "=" '{print $NF}'|sed 's/\"//g'|head -1)
	if [ ! -n "$new_ver" ]; then
		echo -e 指令检索失败,请检查网络. && exit 0
	else
		old_ver=$(md5sum $sh | cut -d' ' -f1)
			if [ "$new_ver" != "$old_ver" ]; then
				wget --no-check-certificate -q -O $sh $sh_new && chmod 777 $sh
				echo -e $RGB33脚本已更新,请再次执行$RGB31[下列]$RGB33指令$RGB
				echo -e ${RGB33}'bash -c "$(curl -sS https://raw.githubusercontent.com/4055020/shell/master/reok)"' && exit 1
			fi
		echo -e $RGB33指令列表已获取.$RGB
	fi
fi
}

check_sys(){
	if [[ -f /etc/redhat-release ]]; then
		check_sys="centos"
	elif cat /etc/issue | grep -q -E -i "debian"; then
		check_sys="debian"
	elif cat /etc/issue | grep -q -E -i "ubuntu"; then
		check_sys="ubuntu"
	elif cat /etc/issue | grep -q -E -i "centos|red hat|redhat"; then
		check_sys="centos"
	elif cat /proc/version | grep -q -E -i "debian"; then
		check_sys="debian"
	elif cat /proc/version | grep -q -E -i "ubuntu"; then
		check_sys="ubuntu"
	elif cat /proc/version | grep -q -E -i "centos|red hat|redhat"; then
		check_sys="centos"
    fi
	bit=`uname -m`

	if [[ ${check_sys} = "centos" ]]; then
		sh_sys="yum"
	else
		sh_sys="apt"
	fi
}

function CheckDependence(){
Dependence='0';
for BIN_DEP in `echo "$1" |sed 's/,/\n/g'`
  do
    if [[ -n "$BIN_DEP" ]]; then
      Founded='0';
      for BIN_PATH in `echo "$PATH" |sed 's/:/\n/g'`
        do
          ls $BIN_PATH/$BIN_DEP >/dev/null 2>&1;
          if [ $? == '0' ]; then
            Founded='1';
            break;
          fi
        done
      if [ "$Founded" == '1' ]; then
        echo -en $RGB32[right]$RGB
      else
        Dependence='1';
        echo -en $RGB31[wrong]$RGB
      fi
      echo -en $RGB36"\t$BIN_DEP\n"$RGB;
    fi
  done
if [ "$Dependence" == '1' ]; then
	$RGB40
	$sh_sys install $BIN_DEP -y -q
	echo -e $RGB36请装好$RGB31[$BIN_DEP]$RGB36再次执行$RGB33[reok]$RGB && exit 1
fi
}

check_sys
CheckDependence wget,curl,awk,grep,sed,cut,cat;
check_sus

while :; do
	case "$1" in

	help)
		echo help;
		exit 0
	;;
	list)
		echo list;
		IPLIST=$2; shift 2
	;;
	check)
		echo check;
		exit 0
	;;
	scan)
		echo scan;
		exit 0
	;;
	ver)
		echo ver;
		exit 0
	;;
	-ssh_port)
		ssh_port=$2; shift 2
		[ ${ssh_port} -eq 22 >/dev/null 2>&1 -o ${ssh_port} -gt 1024 >/dev/null 2>&1 -a ${ssh_port} -lt 65535 >/dev/null 2>&1 ] || { echo "${CWARNING}ssh_port input error! Input range: 22,1025~65534${CEND}"; exit 1; }
	;;
	--)
		shift
	;;
	*)
		read -t 30 -p "请输入命令:" instru
		echo -en $RGB33[指令为]$instru[即将执行]
		echo -en $RGB36 "." && sleep 1s && echo -ne "." && sleep 1s && echo -ne "." && sleep 1s && echo -ne "." && sleep 1s && echo
		check_shell
		exit 1
	;;
	esac
done
